### ISSUE TITLE
Uncompleted FAQ

### ISSUE THREAD

**Issue by vicaba** [oeg-upm/ssn-resource-center#4]
Hello,

I'm starting to learn about ontologies for the semantic web and I'm willing to use the SSN ontology. My problem is that I have a few questions and those questions are adressed by the FAQ, which is uncomplete:

* Which modules/parts of the SSN ontology do I have to use?
* How do I define URIs for my resources?
* Do I use ssn:observationResultTime or ssn:observationSamplingTime?
* Do I reuse or extend the SSN concepts?
* Do I create classes or instances for features and properties?
* How can I validate whether I am correctly using the SSN ontology?
* Do I have to import the SSN ontology in my ontology?

Can you provide with some hints about how to answer each question?

**Comment by ocorcho** [comment]
Hi @vicaba 

You are right, we did not complete that part of the center yet (mostly because of lack of time).

Probably the best option to do it is if you explain to us, here, how you plan to use the SSN Ontology, and then with this in mind, we can generate the concrete answers with examples, so that we can refer to your own example for this purpose. That would be great.

Feel free to upload material using pull requests.

**Comment by vicaba** [comment]
I have access to a database with a lot of home sensor information (sensor readings). I want to model each sensor via the SSN ontology in order to enable applications to access this data homogeneously. I'm only able to retrieve electricity consumption and generation related data, but my objective is to be able to integrate other types of sensor data.

However and as I stated in my first message, I have a lack of understanding about ontologies. I've used Protégé to create a pizza ontology (http://mowl-power.cs.man.ac.uk/protegeowltutorial/resources/ProtegeOWLTutorialP4_v1_3.pdf), but there're things I'm not able to find. In the following list, I'll try to concretize my questions.

* Which mmodules/parts of the SSN ontology do I have to use?
I only know the classes/relations shown in the examples of this site (https://github.com/oeg-upm/ssn-resource-center/wiki/CRTM-SSN, https://github.com/oeg-upm/ssn-resource-center/wiki/Santander). But for sure I need geolocalitazion.

* How do I define URIs for my resources?
I guess that Protégé can help me with that and it's something like domain#class

* Do I use ssn:observationResultTime or ssn:observationSamplingTime?
No idea.

* Do I reuse or extend the SSN concepts?
I've seen that in the examples in this site the SSN concepts are extended by subclasses. I don't know why you do that.

* Do I create classes or instances for features and properties?
Classes if I want to extend the SSN ontology. Instances for each sensor.

* How can I validate whether I am correctly using the SSN ontology?
I don't know.

* Do I have to import the SSN ontology in my ontology?
That's something I've read about... I think it isn't necessary if I don't need a reasoner to validate my ontology (if I create one extending the SSN ontology)

Hope it's enough, if you need more elaboration on the topic, tell me so.
